spring:
  cloud:
    gateway:
      routes:
        - id: servicio-productos
          uri: lb://servicio-productos
          predicates:
            - Path=/api/productos/**
#            - Header=token, \d+
#            - Header=Content-Type,application/json
#            - Method=GET, POST
#            - Query=color, verde
#            - Cookie=color, azul
          filters:
            - StripPrefix=2
            - EjemploCookie=Hola mi mensaje personalizado, usuario, Burandori
        - id: servicio-items
          uri: lb://servicio-items
          predicates:
            - Path=/api/items/**
          filters:
            - StripPrefix=2
            # Otras cabeceras predeterminadas
            - AddRequestHeader=token-request, 123456
            - AddResponseHeader=token-response, 12345678
            - SetResponseHeader=Content-Type, text/plain
            - AddRequestParameter=nombre, burandori

## OTRA FORMA DE DEFINIR EL mensaje, cookieValor, cookieNombre
#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: servicio-productos
#          uri: lb://servicio-productos
#          predicates:
#            - Path=/api/productos/**
#          filters:
#            - StripPrefix=2
#            - name: Ejemplo
#              args:
#                mensaje: Hola mi mensaje personalizado
#                cookieValor: usuario
#                cookieNombre: BrandonLee
#        - id: servicio-items
#          uri: lb://servicio-items
#          predicates:
#            - Path=/api/items/**
#          filters:
#            - StripPrefix=2