#  spring: es la raíz de la configuración de Spring.
#  cloud: indica que es una configuración específica para aplicaciones en la nube.
#  gateway: indica que se está configurando Spring Cloud Gateway.
#  routes: especifica las rutas que se deben configurar.
#  En las siguientes líneas se definen dos rutas:
#
#  servicio-productos: es el identificador de la ruta. Se utilizará para hacer referencia a esta ruta en otras partes de la configuración.
#  uri: indica la dirección del servicio al que se está redirigiendo. lb://servicio-productos significa que se está utilizando un balanceador de carga para redirigir la solicitud al servicio "servicio-productos".
#  predicates: se utiliza para definir las condiciones que deben cumplirse para que una solicitud sea enrutada a esta ruta. En este caso, las condiciones son:
#  Path=/api/productos/**: la solicitud debe tener la ruta /api/productos seguido de cualquier número de sub-rutas.
#  Header=token, \d+: el encabezado de la solicitud debe tener una clave llamada token y su valor debe ser un número de uno o más dígitos.
#  Header=Content-Type,application/json: el encabezado de la solicitud debe tener una clave llamada Content-Type y su valor debe ser application/json.
#  Method=GET, POST: la solicitud debe ser una solicitud GET o POST.
#  Query=color, verde: el parámetro de consulta debe ser color y su valor debe ser verde.
#  Cookie=color, azul: la cookie debe tener una clave llamada color y su valor debe ser azul.
#  filters: se utiliza para definir los filtros que se deben aplicar a la solicitud antes de que se enrutada a la ruta. En este caso, los filtros son:
#  StripPrefix=2: elimina los dos primeros segmentos de la ruta (/api/productos).
#  EjemploCookie=Hola mi mensaje personalizado, usuario, Burandori: agrega una cookie llamada EjemploCookie con un valor de Hola mi mensaje personalizado y dos atributos adicionales usuario y Burandori.
#  La segunda ruta (servicio-items) es similar, pero tiene diferentes condiciones y filtros. En este caso, solo hay una condición (Path=/api/items/**) y cuatro filtros:
#
#  StripPrefix=2: elimina los dos primeros segmentos de la ruta (/api/items).
#  AddRequestHeader=token-request, 123456: agrega un encabezado de solicitud llamado token-request con un valor de 123456.
#  AddResponseHeader=token-response, 12345678: agrega un encabezado de respuesta llamado token-response con un valor de 12345678.
#  SetResponseHeader=Content-Type, text/plain: establece el encabezado de respuesta Content-Type a text/plain.
#  AddRequestParameter=nombre, burandori: agrega un parámetro de consulta llamado nombre con un valor de burandori.

spring:
  cloud:
    gateway:
      routes:
        - id: servicio-productos
          uri: lb://servicio-productos
          predicates:
            - Path=/api/productos/**
#            - Header=token, \d+
#            - Header=Content-Type,application/json
#            - Method=GET, POST
#            - Query=color, verde
#            - Cookie=color, azul
          filters:
            - StripPrefix=2
            - EjemploCookie=Hola mi mensaje personalizado, usuario, Burandori
        - id: servicio-items
          uri: lb://servicio-items
          predicates:
            - Path=/api/items/**
          filters:
            - StripPrefix=2
            # Otras cabeceras predeterminadas
            - AddRequestHeader=token-request, 123456
            - AddResponseHeader=token-response, 12345678
            - SetResponseHeader=Content-Type, text/plain
            - AddRequestParameter=nombre, burandori

## OTRA FORMA DE DEFINIR EL mensaje, cookieValor, cookieNombre
#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: servicio-productos
#          uri: lb://servicio-productos
#          predicates:
#            - Path=/api/productos/**
#          filters:
#            - StripPrefix=2
#            - name: Ejemplo
#              args:
#                mensaje: Hola mi mensaje personalizado
#                cookieValor: usuario
#                cookieNombre: BrandonLee
#        - id: servicio-items
#          uri: lb://servicio-items
#          predicates:
#            - Path=/api/items/**
#          filters:
#            - StripPrefix=2